### ISSUE TITLE
Research Content: Templates for Business contracts assigned

### ISSUE THREAD

**Issue by Johnny4design** [zuri-training/t_c_gen_team_72#31]

**Comment by MariamAbosede** [comment]
[Construction contract agreement template ](https://drive.google.com/file/d/1xqbh8WY-jT3UrRdw2kifMsREDscQNQin/view?usp=drivesdk)

**Comment by Sophiyha** [comment]
I've submitted the task you assigned to me.

**Comment by Sophiyha** [comment]
Service Contract template submitted

**Comment by Glorygarba** [comment]
Freelance Contract Template submitted

**Comment by Faithly76** [comment]
Financial contract template submitted.

**Comment by Temabo** [comment]
Information technology contract template submitted

**Comment by OnyinyeOkoye** [comment]
Software as a Service contract template submitted

**Comment by emecuz** [comment]
Insurance contract template submitted
